services:
    vkc.datahub.shared.documents:
        class: VKC\DataHub\SharedBundle\Service\DocumentsService
        calls:
            - [setConnection, [@doctrine_mongodb.odm.default_connection]]
            - [setDatabaseName, [%vkc_data_hub_shared.database_name%]]
