language: php

php:
  - '5.6'
  - '7.0'

services:
  - mongodb

before_install:
  - echo 'extension = "mongo.so"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - phpenv config-add travis.ini

install:
  - composer install

before_script:
  - ./scripts/update_install
  - app/console app:setup
  - app/console doctrine:mongodb:fixtures:load --append

script:
  - ./scripts/run_tests
