language: php
php:
  - '5.6'
services: mongodb
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y php5-cli php5-intl php5-mcrypt
install:
  - pecl install mongo
  - composer install
