language: php
php:
  - '5.6'
services: mongodb
before_install:
  - perl install 5.10
  - sudo apt-get -qq update
  - sudo apt-get install -y php5-cli php5-intl php5-mcrypt
install:
  - cpan install catmandu
  - yes '' | pecl install -f mongo
  - composer install
before_script:
  - ./scripts/update_install
  - app/console app:setup
  - app/console doctrine:mongodb:fixtures:load --append
script:
  - ./scripts/run_tests
