language: php

php:
  - '5.6'
  - '7.0'

services:
  - mongodb

install:
  - if [[ $TRAVIS_PHP_VERSION != hhvm ]]; then phpenv config-rm xdebug.ini; fi;
  - composer install

before_script:
  - echo 'extension = "mongo.so"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - ./scripts/update_install
  - app/console app:setup
  - app/console doctrine:mongodb:fixtures:load --append

script:
  - ./scripts/run_tests
