# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    java: %java_path%
    filters:
        cssrewrite: ~
        yui_css:
            jar: %kernel.root_dir%/../bin/yuicompressor.jar
        yui_js:
            jar: %kernel.root_dir%/../bin/yuicompressor.jar
        lessphp:
            file:     "%kernel.root_dir%/../vendor/oyejorge/less.php/lessc.inc.php"
            apply_to: "\.less$"
