imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: assetic.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: %trusted_proxies%
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  session.handler.mongo
    fragments:       ~
    http_method_override: true
    request:
        formats:
            lidoxml: "application/lido+xml"

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        service_name: '%service_name%'
        service_organisation_website: '%service_organisation_website%'
        service_organisation: '%service_organisation%'
        service_address: '%service_address%'
    form:
        resources: 
            - 'bootstrap_3_layout.html.twig'

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# Non-core

fos_oauth_server:
    db_driver: mongodb       # Drivers available: orm, mongodb, or propel
    client_class:        "DataHub\\OAuthBundle\\Document\\Client"
    access_token_class:  "DataHub\\OAuthBundle\\Document\\AccessToken"
    refresh_token_class: "DataHub\\OAuthBundle\\Document\\RefreshToken"
    auth_code_class:     "DataHub\\OAuthBundle\\Document\\AuthCode"
    service:
        # user_provider: fos_user.user_provider.username
        user_provider: datahub.security.user_provider.username
        options:
            supported_scopes: internal web external
            access_token_lifetime: %access_token_lifetime%

nelmio_api_doc:
    sandbox:
        authentication:
            name: access_token
            delivery: query
    motd:
        template: 'DataHubOAuthBundle::Documentation/motd.html.twig'

fos_rest:
    param_fetcher_listener: true
    body_listener:
        enabled: true
        throw_exception_on_unsupported_content_type: true
        decoders:
            lidoxml: datahub.resource_api.decoder.xml
    format_listener:
        rules:
            -
                path: '^/api/.*?\.xml$'
                host: ~
                prefer_extension: true
                fallback_format: xml
                priorities: [xml, json]
            -
                path: '^/api'
                host: ~
                prefer_extension: true
                fallback_format: json
                priorities: [json]
            -
                path: '^/oauth'
                host: ~
                prefer_extension: true
                fallback_format: html
                priorities: [html]
            -
                path: ~
                host: ~
                prefer_extension: true
                fallback_format: html
                priorities: [html]
    view:
        formats:
            json: true
            xml: true
            lidoxml: true
        mime_types:
            formats:
                lidoxml: ['application/lido+xml']
        view_response_listener: true
    exception:
        enabled: true
  #  disable_csrf_role: ROLE_API
    allowed_methods_listener: true
    access_denied_listener:
        # all requests using the 'json' format will return a 403 on an access denied violation
        json: true
        xml: true
        lidoxml: true
    routing_loader:
        default_format: json

nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: []
        allow_headers: []
        allow_methods: []
        expose_headers: []
        max_age: 0
        hosts: []
    paths:
        '^/':
            allow_origin: ['*']
            allow_credentials: true
            allow_headers: ['*']
            expose_headers: ['Content-Type', 'Content-Disposition']
            allow_methods: ['POST', 'PUT', 'PATCH', 'GET', 'DELETE', 'OPTIONS']
            max_age: 60

doctrine_mongodb:
    default_database: %mongodb_database%
    connections:
        default:
            server: %mongodb_server%
            options:
                username: %mongodb_user%
                password: %mongodb_password%
                db: admin
    document_managers:
        default:
            auto_mapping: true

stof_doctrine_extensions:
    default_locale: en_US
    mongodb:
        default:
            timestampable: true # not needed: listeners are not enabled by default

# OAI endpoint config, see parameters.yml
data_hub_oai:
    datahub_oai_repo_name: %datahub_oai_repo_name%
    datahub_oai_contact_email: %datahub_oai_contact_email%
    datahub_oai_pagination_num_records: %datahub_oai_pagination_num_records%
