datahub_resource_api:
    resource: "@DataHubResourceAPIBundle/Resources/config/routing.yml"
    type:     rest
    prefix:   /api/v1/

datahub_oai:
    resource: "@DataHubOAIBundle/Controller/"
    type:     annotation
    prefix:   /oai/

datahub_static_docs_oai:
    path: /docs/oai
    defaults:
        _controller: FrameworkBundle:Template:template
        template:    static/docs/oai.html.twig

datahub_oauth:
    resource: "@DataHubOAuthBundle/Controller/"
    type:     annotation
    prefix:   /oauth/

datahub_users:
    resource: "@DataHubUserBundle/Controller/"
    type:     annotation
    prefix:   /user

datahub_shared:
    resource: "@DataHubSharedBundle/Controller"
    type:     annotation
    prefix:   /

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /docs/api

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"

datahub_log:
    resource: "@DataHubPipelineBundle/Controller/"
    type:     annotation
    prefix:   /
