datahub_resource_api:
    resource: "@DataHubResourceAPIBundle/Resources/config/routing.yml"
    type:     rest
    prefix:   /api/v1/

datahub_oai:
    resource: "@DataHubOAIBundle/Controller/"
    type:     annotation
    prefix:   /oai/

datahub_oauth:
    resource: "@DataHubOAuthBundle/Controller/"
    type:     annotation
    prefix:   /admin/oauth/

datahub_users:
    resource: "@DataHubUserBundle/Controller/"
    type:     annotation
    prefix:   /admin/users

datahub_shared:
    resource: "@DataHubSharedBundle/Controller"
    type:     annotation
    prefix:   /

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /docs/api

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix: /admin

fos_user_resetting:
     resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
     prefix: /resetting

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"
