datahub_resource_api:
    resource: "@DataHubResourceAPIBundle/Resources/config/routing.yml"
    type:     rest
    prefix:   /api/v1/

datahub_oai:
    resource: "@DataHubOAIBundle/Controller/"
    type:     annotation
    prefix:   /oai/

datahub_oauth:
    resource: "@DataHubOAuthBundle/Controller/"
    type:     annotation
    prefix:   /oauth/

datahub_users:
    resource: "@DataHubUserBundle/Controller/"
    type:     annotation
    prefix:   /users/

datahub_shared:
    resource: "@DataHubSharedBundle/Controller"
    type:     annotation
    prefix:   /

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /docs/api

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"
