# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    providers:
        user_provider:
            mongodb:
                class: DataHub\UserBundle\Document\User
                property: username

    role_hierarchy:
        ROLE_MANAGER: ROLE_CONSUMER
        ROLE_ADMIN: ROLE_MANAGER

    encoders:
        DataHub\UserBundle\Document\User: bcrypt

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~

            guard:
                authenticators:
                    - datahub.security.login_form_authenticator
            
            logout:
                path: /user/logout
# security:
#     encoders:
#         FOS\UserBundle\Model\UserInterface: bcrypt

#     role_hierarchy:
#         ROLE_ADMIN:       [ROLE_USER]
#         ROLE_SUPER_ADMIN: ROLE_ADMIN

#     # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
#     providers:
#         fos_userbundle:
#             id: fos_user.user_provider.username_email

#     firewalls:
#         # disables authentication for assets and the profiler, adapt it according to your needs
#         dev:
#             pattern: ^/(_(profiler|wdt)|css|images|js)/
#             security: false

#         oauth_token:
#             pattern:    ^/oauth/v2/token
#             security:   false

#         oauth_revoke:
#             pattern:    ^/oauth/v2/revoke
#             security:   false

#         api:
#             pattern:    '^/api/.+'
#             fos_oauth:  true
#             stateless:  true
#             anonymous:  ~

#         oai:
#             pattern:    '^/oai'
#             fos_oauth:  true
#             stateless:  true
#             anonymous:  ~

#         main:
#             pattern: ^/
#             form_login:
#                 provider: fos_userbundle
#                 login_path: fos_user_security_login
#                 check_path: fos_user_security_check
#                 default_target_path: /
#             logout:
#                 path: fos_user_security_logout
#             anonymous:    true
#             remember_me:
#                 secret:      "%secret%"
#                 lifetime: 2592000 # 1 month in seconds
#                 path:     /

#     access_control:
#         - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: %security_requires_channel% }
#         - { path: ^/register/$, role: ROLE_SUPER_ADMIN, requires_channel: %security_requires_channel% }
#         # - { path: ^/api_docs.html$, role:ROLE_SUPER_ADMIN, requires_channel: %security_requires_channel% }
#         - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: %security_requires_channel% }
#         - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: %security_requires_channel% }
#         - { path: ^/api,  role: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: %security_requires_channel%, methods: %public_api_method_access% }
#         - { path: ^/api,  role: IS_AUTHENTICATED_FULLY, requires_channel: %security_requires_channel% }
#         - { path: ^/oai,  role: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: %security_requires_channel%, methods: %public_api_method_access% }
#         - { path: ^/oai, role: IS_AUTHENTICATED_FULLY, requires_channel: %security_requires_channel% }
#         - { path: ^/, role: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: %security_requires_channel% }
