# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    mongo.session.options:
        database: %mongodb_database%
        collection: Sessions

services:
    mongo.connection:
        class: MongoDoctrine\MongoDB\Connection
        factory_service: doctrine.odm.mongodb.document_manager
        factory_method: getConnection
        calls:
           - [initialize, []]
    mongo:
        class: Mongo
        factory_service: mongo.connection
        factory_method: getMongo
    session.handler.mongo:
        class: "Symfony\\Component\\HttpFoundation\Session\\Storage\Handler\\MongoDbSessionHandler"
        arguments: ['@mongo', '%mongo.session.options%']
    twig.text_extension:
        class: Twig_Extensions_Extension_Text
        tags:
            - name: twig.extension
