services:
    datahub.oai.http_foundation_factory:
        class: Symfony\Bridge\PsrHttpMessage\Factory\HttpFoundationFactory

    datahub.oai.repository:
        class: DataHub\OAIBundle\Repository\Repository
        arguments: ['@datahub.resource.data']
        calls:
            - [setRepositoryName, [%data_hub_oai.datahub_oai_repo_name%]]
            - [setContactEmail, [%data_hub_oai.datahub_oai_contact_email%]]
            - [setPaginationSize, [%data_hub_oai.datahub_oai_pagination_num_records%]]
            - method: setBaseUrl
              arguments:
                  - '@request_stack'
