services:
    # XML decoder
    datahub.resource_api.decoder.xml:
        class: DataHub\ResourceAPIBundle\Decoder\XmlDecoder
        arguments: ['@logger', '@datahub.resource.builder.converter.factory']
