services:
    vkc.datahub.resource_api.form.type.data_form_type:
        class: VKC\DataHub\ResourceAPIBundle\Form\Type\DataFormType
        calls:
            - [setDataConverters, [@vkc.datahub.resource.data_converters]]
        tags:
            - { name: form.type }
    vkc.datahub.resource_api.decoder.lidoxml:
        class: VKC\DataHub\ResourceAPIBundle\Decoder\LidoXmlDecoder

    # This part makes .lidoxml output possible in rest service
    vkc.datahub.resource_api.view_handler.lidoxml:
        class: VKC\DataHub\ResourceAPIBundle\View\LidoXMLViewHandler

    vkc.datahub.resource_api.view_handler:
        parent: fos_rest.view_handler.default
        calls:
            - ['registerHandler', ['lidoxml', [@vkc.datahub.resource_api.view_handler.lidoxml, 'createResponse'] ] ]